### ISSUE TITLE
`styler.equals::style_pkg()` makes fewer corrections than `styler::style_pkg()`

### ISSUE THREAD

**Issue by eitsupi** [Robinlovelace/styler.equals#3]
From pola-rs/r-polars#214

Thanks for working on this.
I tried `styler.equals::style_pkg()` on the polars package, but it was necessary to run it after `styler::style_pkg()` because the modifications were not made as expected.
Are differences other than assign operators intentional?
Or do you plan to make all but the assignment operator equivalent to `styler::style_pkg()` in the future?

**Comment by Robinlovelace** [comment]
> Or do you plan to make all but the assignment operator equivalent to `styler::style_pkg()` in the future?

The intention was for everything to be equivalent now. Indeed that's what I thought would happen based on what's in this package. Can you provide more detail on what did not change with this package vs `styler`? Thanks for reporting and sorry for slow response btw.

**Comment by Robinlovelace** [comment]
OK update on this:

> Currently, all the style guide is doing is to replace <- with =

From https://github.com/lorenzwalthert/styler.yours README (I had incorrectly assumed `tidyverse` as default).

So work to do!

**Comment by Robinlovelace** [comment]
Not that much work to do... It's to change this

https://github.com/Robinlovelace/styler.equals/blob/d4e4fc930f3fe1eab19f1cb85adff368ad14d1bf/R/core.R#L15-L56

So it's more like 

https://github.com/r-lib/styler/blob/8e9ac82333c2a0036a1653a029b6437008650f34/R/style-guides.R#L65-L257

Any ideas/help with that v. welcome, I guess a reasonable starting point would be try the whole tidyverse. Personally I'd like a few tweaks compared with the tidyverse, favouring `if(` over `if (` for example but happy to go in whichever direction will be most use to the most people.

**Comment by eitsupi** [comment]
Thanks for the reply. Perhaps even keep a few different styles in the package?

**Comment by Robinlovelace** [comment]
Finally looking at this...

**Comment by Robinlovelace** [comment]
I think this is fixed now..
